[common]
# 监听端口
bind_port = 7000
# 面板端口
dashboard_port = 7810
# 登录面板账号设置
dashboard_user = admin  
dashboard_pwd = 123456
# 设置http及https协议下代理端口（非重要）
vhost_http_port = 7080
vhost_https_port = 7081
# 身份验证
token = 123456
